### ISSUE TITLE
Transfer ECOV via ecoswap program

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/ecoverse-dao#10]
### Description
Transfer an spl-token (ECOV) via a unified Rust program which orchestrates both the transfer of SOL & the transfer of ECOV **_concurrently_**.

### Tasks
 - [x] user the .ts client to feed the right PDA to the Rust program 
 - [x] hard code into the Rust program the correct seed (only the seed is enough - no bump)
 - [x] re-create the PDA inside the Rust program from seed
 - [x] ensure the program callers are authorized callers
 - [x] multiply amount of SOL by 10E-9 to convert from SOL Lamports to ECOV units
 - [x] send right amount of ECOV to whomever got deducted of SOL
