### ISSUE TITLE
Create Associated Token Account (ATA)

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/ecoverse-dao#11]
### Description
Send an SPL-token to a user that doesn't own an ATA account for that token yet. 

---

### Tasks
 - [x] set up the spl-token transfer instruction in Rust
 - [x] **find** an ATA for the receiver in TypeScript
(the person funding the creation of the ATA is either the spl-token sender OR the ATA owner himself)
 - [x] **derive** an ATA in the frontend using the web3.js Solana function `get_associated_token_account()`
 - [x] pass the publicKey of the receiver's ATA account from the .ts frontend to the Rust contract
 - [x] send an spl-token to the ATA account via the Rust smart contract
 - [x] **create** an ATA programmatically in the Rust contract

### Final Flow
Assume George is an _Ecoverse_ user and the recipient of ECOV tokens
 - [x] **find** George's ATA in TypeScript client - derive it from George's wallet and the ECOV token mint account
 - [x] pass George's ATA to the Rust program's instructions via the TypeScript frontend client
 - [x] read from the program instructions George's ATA and **create/initialize** it programmatically in Rust, so that it's active 
(use the Rust function `spl_associated_token_account::instruction
    ::create_associated_token_account_idempotent()` )
