### ISSUE TITLE
transfer spl-tokens

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/ecoverse-dao#12]
### Description
Build a standalone Rust program with corresponding TypeScript client to transfer spl-tokens from a sender's Associated Token Account to a receiver's Associated Token Account

### Tasks
 - [x] build Rust program to transfer tokens
 - [x] build TypeScript client to invoke the program
 - [x] perform token converstion (10E9) in the smart contract
 - [x] transfer tokens from your Phantom wallet and back
 - [x] perform transfer using system wallet &rarr; `createKeypairfromFile("MY_PATH")`
 - [x] perform transfer using Phantom wallet &rarr; `Keypair.fromSecretKey(bs58.decode("MY_SECRETKEY))`
