### ISSUE TITLE
Dev Docs

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/ecoverse-dao#6]
### Tasks
  - Docs for ECOSWAP contract
     - [x] document the logic of the primary contract functions
     - [x] doc all `.env` vars

  - Docs for ECOV client
      - [x] document flow to mint and remint SPL-tokens
