### ISSUE TITLE
'Find' a Solana Program Derive Address (PDA)

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/ecoverse-dao#7]
### What we want to do
We want to transfer (using Program instructions) custom SPL token (namely ECOV) from BBox's liquidity pool account to an Ecoverse user's wallet?

### How to
ECOV are a type of spl-token. Transferring programmatically spl-tokens requires the ECOV host wallet address to be owned by a program-derived address (PDA), derived from the program that minted ECOV in the first place. Hence, let's:

### Tasks
- [X] generate/find a PDA for the ECOV program_id (you actually don't need to reference the program or origin to derive a PDA)
- [X] every PDA is identified by: an address, a seed, and a bump. Retrieve and save these 3 pieces of info
- [X] use a TypeScript client to interact with the Rust program and find a PDA
